version: "3"

services:
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    volumes:
      - "/:/host:ro,rslave"
    command:
      - "--path.rootfs=/host"
      - "--collector.netclass.ignored-devices=(veth|br).*"
      - "--collector.netdev.device-exclude=(veth|br).*"
      - "--web.listen-address=0.0.0.0:9100"
    networks:
      - traefik_proxy
    pid: host
    restart: unless-stopped

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - traefik_proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - prometheus
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.tls=true"

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  traefik_proxy:
    external: true
