version: "3"

services:
  home:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ./assets/:/www/assets
    user: "1002" # homer user uid
    networks:
      - traefik_proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homer.tls=true"

networks:
  traefik_proxy:
    external: true
