version: "3"

services:
  influxdb:
    image: influxdb:1.8
    volumes:
      - influxdb-storage:/var/lib/influxdb
    env_file:
      - ".env"
    networks:
      - traefik_proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.influxdb.tls.options=old@file"
      - "traefik.http.routers.influxdb.tls=true"
      - "traefik.http.middlewares.influxdb-corsheaders.headers.accesscontrolallowmethods=GET,OPTIONS,POST"
      - "traefik.http.middlewares.influxdb-corsheaders.headers.accesscontrolalloworiginlist=http://localhost:3000,https://controlhub.clementlize.com"
      - "traefik.http.middlewares.influxdb-corsheaders.headers.accessControlAllowHeaders=Authorization,Content-Type"
      - "traefik.http.routers.influxdb.middlewares=hsts-header@file,influxdb-corsheaders@docker"

  chronograf:
    image: chronograf:latest
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    env_file:
      - ".env"
    networks:
      - traefik_proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chronograf.tls=true"

volumes:
  influxdb-storage: {}
  chronograf-storage: {}

networks:
  traefik_proxy:
    external: true
