version: "3"

services:
  status:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /media/docker/uptime-kuma:/app/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
